### ISSUE TITLE
the generic term "Authorization Token" to describe an access_token is really confusing!

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#17]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#34111-authorization-client

The use of the term "Authorization Token" to refer to the OAuth2 access_token is super confusing to readers familiar with the HL7 SMART spec and should be changed.

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
seems reasonable to change to Access Token when in narrative.

**Comment by JohnMoehrke** [comment]
Will make the change Friday morning after morning changes.
