### ISSUE TITLE
oh my goodness, another capabilities endpoints!?!?! Don't we have enough already?

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#18]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#310341-authorization-server-metadata-request

Why is IHE creating a duplicative capability mechanism? SMART already has two. Instead, this profile should extend the existing .well-known/smart-configuration json file.

- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by joostreuzel** [comment]
The IUA the meta-data document tells something about the *Authorization Server*, where the capability statement IUA code is defined for the *Resource Server*. From that perspective, adding a Authorization Server metadata document to an resource server is not so logical. 

In SMART the resource server and authorization server are not as separated as in IUA (typically even combined in an EHR instance). Effectively, by combining the two IUA server actors, the meta-data transaction can be handled by the same service that serves the FHIR capability statement. 

Interestingly, the [SMART-server configuration document](http://hl7.org/fhir/smart-app-launch/conformance/index.html#using-well-known) seems to be based on RFC8414, but does not explicitly mention that. Instead it mentions RFC5785 (mistake?). However, as the fields and semantics are similar to those of RFC8414, the IUA AS meta-data document can be easily combined with the SMART server configuration document.

**Comment by isaacvetter** [comment]
>the IUA AS meta-data document can be easily combined with the SMART server configuration document.

Can we state this in this profile? Even as an example of what the resulting json file would look like, e.g.:

```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "authorization_endpoint": "https://ehr.example.com/auth/authorize",
  "token_endpoint": "https://ehr.example.com/auth/token",
  "token_endpoint_auth_methods_supported": ["client_secret_basic"],
  "registration_endpoint": "https://ehr.example.com/auth/register",
  "scopes_supported": ["openid", "profile", "launch", "launch/patient", "patient/*.*", "user/*.*", "offline_access"],
  "response_types_supported": ["code", "code id_token", "id_token", "refresh_token"],
  "management_endpoint": "https://ehr.example.com/user/manage"
  "introspection_endpoint": "https://ehr.example.com/user/introspect"
  "revocation_endpoint": "https://ehr.example.com/user/revoke",
  "capabilities": ["launch-ehr", "client-public", "client-confidential-symmetric", "context-ehr-patient", "sso-openid-connect"],
  "issuer": "",
  "jwks_uri" : "",
  "grant_types_supported" :"",
  "token_endpoint_auth_methods_supported": "",
  "introspection_endpoint_auth_methods_supported" : ""
}
```

**Comment by msmock** [comment]
Will be mentioned in an open issue.
