### ISSUE TITLE
consider referencing HL7's SMART

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#19]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#3713-referenced-standards

HL7's SMART standard is the defacto implementation of OAuth in healthcare per the US government. Did ya'll consider referencing it? From reading this profile, it's not obvious. 

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by joostreuzel** [comment]
It has been considered to some level, but was not included. See discussion in #21 for some of the reasons.

Personally I think SMART covers a different set of use-cases and setups (EHR-centric launch) than those supported by this profile, which are not centered around EHR usage. Open question: Do we want to explicitly include the SMART (launch) use cases, or shall we simply refer to SMART for those?

**Comment by isaacvetter** [comment]
Talked through this in the IHE call this morning -- 
Perhaps some introductory content providing an explanation of how the IUA profile is different from SMART to implementers who may have already implemented SMART.
