### ISSUE TITLE
don't allow plain as a code_challenge_method in PKCE

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#20]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#37141-get-authorization-token-request

>code_challenge_method (OPTIONAL): Indicator used for the code challenge transformation method. It's value MAY be plain or S256 [OAuth 2.1, Section 9.8].

I might be mistaken, but permitting plain here radically decreases the value of using the optional code_challenge, right? Why permit plain when support is already optional? You should remove support for plain.

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by msmock** [comment]
Made the change on working branch to be merged today
