### ISSUE TITLE
no support for launch tokens?

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#21]
HL7's SMART spec's definition of a launch token is incredibly useful in production environments for patient and user-facing apps.

I strongly suspect that not carrying it over is a mistake and fear that other valuable features were likely missed because the the absence of a thorough crosswalk between the dominant healthcare standard for the use of OAuth2 and this profile. 

Please describe how this profile differs from HL7's SMART. 

- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by joostreuzel** [comment]
The current specification indeed does not refer to SMART. I see mainly four reasons for that:
* SMART is bound to FHIR, where the IUA profile should also be usable for non-FHIR API's. For example, profiles may want to use DICOM-WEB in the future. 
* SMART is directed towards a set of use cases, eg. "EMR-launch". IUA contains use-cases not covered by SMART, such as community-level data exchange, or service-2-service integrations. 
* A number of IHE profiles are using FHIR operations and FHIR messaging. I'm not aware how SMART scopes are covering these types of interactions.
* Technically, SMART is creating a non-further specified dependency between the Authorization Server and the app launching applications, by embedding the launch context into the authorization mechanisms. In SMART the authorization server is aware of the launch context and the associated permissions. This may work in EMR cases where authorization and data access are controlled from the same (EMR) system, but these are not so obvious in other situations. How would a generic authorization server be able to interpret the launch-id parameter?

**Comment by isaacvetter** [comment]
Hi @joostreuzel !

Clearly, you've referenced the HL7 SMART spec quite a bit! This profile is actually intended to react to and fill in gaps in that other spec, isn't it? I'm just asking if that can be made more explicit. 

> IUA contains use-cases not covered by SMART
The use-case introduced in the Problem statement describes patient-facing apps using the auth code flow, which is exactly covered by SMART, right?. 

>  IUA is compatible with [SMART backend services].
Can we explicitly state this in the profile to discourage drift over time? 

Isaac

> I'm not aware how SMART scopes are covering these types of interactions.
Yeah, you're right. SMART doesn't define a scope syntax for FHIR messaging or operations. 

>How would a generic authorization server be able to interpret the launch-id parameter?
In the implementations that I've seen over the years, the workflow system (EHR) has a trust relationship with the AS and asks the AS for the launch token before launching the SMART app.

**Comment by joostreuzel** [comment]
You are right in that it is mentioned in the use-cases, but the SMART EHR launch sequence is not embedded in the transactions of this profile. How would you recommend to add these (if necessary)?

I agree that adding a reference with SMART backend services makes a lot of sense.

**Comment by joostreuzel** [comment]
> In the implementations that I've seen over the years, the workflow system (EHR) has a trust relationship with the AS and asks the AS for the launch token before launching the SMART app.

That would be an interesting API to standardize...
