### ISSUE TITLE
please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with SMART's draft.

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#22]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#3102-introspect-token

Please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with SMART's draft -- https://github.com/HL7/smart-app-launch/pull/306/files

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by joostreuzel** [comment]
As far as I can see, there is no real conflict:
* IUA is based on the standard RFC as is SMART. 
* IUA mandates support for access tokens only, but implementations can opt to support other token types (eg., id-tokens) as well. 
* Main differences lie in the claims added to the base standard. There are no naming conflicts there. There may be an overlap in the XUA and SMART claims (eg., subject reference).
* Some fields are mandatory in IUA, optional in SMART (e.g the audience claim). It would be a non-breaking change to add them to a SMART introspect result, making the SMART introspect compatible with IUA
* In certain cases, some SMART claims are mandatory where they are not specified in IUA. That makes that IUA introspect is not 100% conforming to SMART. It would not be a violation to add them to a IUA introspect result.

My conclusion: An implementation will be able to combine SMART and IUA introspect requirements in a single endpoint.

Note: happy to see the introspect addition to SMART!

**Comment by msmock** [comment]
We are not constraining the transaction
