### ISSUE TITLE
please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with SMART's draft.

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#23]
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#3102-introspect-token

Please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with [SMART's draft](https://github.com/HL7/smart-app-launch/pull/306/files).

**Comment by joostreuzel** [comment]
duplicate of #22
