### ISSUE TITLE
Figure 34.4-1 in IUA needs updates

### ISSUE THREAD

**Issue by MaryLJ** [IHE/ITI.IUA#41]
**Section Number** Figure 34.4-1

**Issue** ITI-71 and ITI-72 in Figure 34.4-1 need to be updated to change  "authorization" to "access"

**Proposed Change** *Change the word "authorization" to "access"

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by msmock** [comment]
It's figure 34.1-1 now. Need to be fixed.
