### ISSUE TITLE
notes in tables

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.IUA#43]
**Section Number** *Table 34.1-1*

**Issue** *in the optionality column there is the "Note 1 " text to indicate that a note exists for this value of optionality... Optianility value and Note text have the same format.. *

**Proposed Change** *change the note text size or put it bold or italic or just like in table 34.1-2 put the text whithin two brakets (Note 1). the best wuold it be ti have it like it is in pdf*

**Priority**: LOW

**Comment by msmock** [comment]
Fixed in branch Work-In-Progress
