### ISSUE TITLE
CapabilityStatement.rest.security.service just fro Resource server or also for authorization client?

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.IUA#44]
**Section Number** *34.1.1.1*

**Issue** *This section describes the authorization Client actor and in the second paragraphs it says "an Authorization Client should query the capabilities endpoint on the Resource Server to determine if the Resource Server supports IUA. The element CapabilityStatement.rest.security.service will be populated with the code "IUA" at system canonical URL "http://profiles.ihe.net/fhir/ihe.securityTypes/CodeSystem/securityTypes". The CodeSystem can be retrieved from the IHE FHIR GitHub repository, codesystem-IHE_securitytypes.xml". 
I have to issues :
1) i don't like the second sentence because it is more a requirement for the Resource server actor than an Authorization client acotr. I understand the meaning the to explaing what they have to search in the capability statement of the server, but we have already that requirment in section 34.1.1.3
2)i'm wondering if we should say something regarding the fact that if the authorization client has a capabilityStatement resource the CapabilityStatement.rest.security.service should be valued with IUA*

**Proposed Change** * for the first issue just delete the second sentence. for the second i think that an IG that involves IUA will need both client and server capability statements resources to clearly states the support for IUA*

**Priority**: medium

**Comment by JohnMoehrke** [comment]
I agree these clarifications are good.

There are other indicators in the welknown space that SMART is leveraging, should we do so as well?
