### ISSUE TITLE
Consider referencing the FAPI 2.0 profile

### ISSUE THREAD

**Issue by steinarnoem** [IHE/ITI.IUA#49]
Regarding Security Considerations (e.g. 3.71.5 and 3.102.5 )

OIDF has been working with a security profile for OAuth called FAPI that is suitable for high-risk domains. The profile was created to satisfy the requirements of the PSD2 initiatives (Open Banking, Berlin Group), which is why the name points to the financial sector (Financial Grade APIs). Although the name suggest the profile is tailored for the financial market, the specification states that "The Financial-grade API security profile can be applied to online services in any market area that requires a higher level of security than provided by standard OAuth or OpenID Connect".

This profile is, or will be, supported by a number of commercial AS/OP products, as the profile already is used by the two major PSD2 initiatives in Europe in addition to other similar initiatives in other parts of the world.

I think it would make sense for IUA to point at FAPI 2.0 as a "mechanical" security profile for high-risk scenarios. This would ensure a focus on an appropriate level of security for IUA and would make interoperability easier as most AS/OP vendors already conform to this standard.

I have no idea of how you should prioritize this, but I do think the advantages to pointing to an exisiting international standard should be discussed thoroughly.

**Comment by joostreuzel** [comment]
The FAPI profile references RFCs that utilize TLS with client certificates, and mechanisms to bind access tokens to the certificates used to create those TLS connections. Though this provides additional security, it also provides additional requirements to all actors defined in the IUA profile. 

All of these actors must support these requirements to be interoperable. Moreover, this would not allow for use-cases with non-confidential (e.g. browser-based or mobile) applications as many of these user-agents do not support this type of token binding.  Similarly, many (public) cloud infrastructures would not directly support such a model (utilizing TLS-offloading services).

As such, I think referring to FAPI is more than 'a security consideration' that would apply to some of the implementations. Either we would need to include it integrally in the profile, or it is kept out of scope for this profile and is optionally implemented on project level (with support from the various technology providers). Give the impact of the FAPI specifications I would opt for the latter...

**Comment by msmock** [comment]
Evaluated in Feb 2021 F2F. Agreed upon that no action is required.
