### ISSUE TITLE
unclear sentence 

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#5]
**Section Number** 34.4.1.2

**Issue**  I cannot parse this sentence: Typically in health related environments, a healthcare professional accesses patients or organization related data (resources) for which the healthcare professional is not the "legal owner", but may access according to the access policies of the environment. To avoid any misunderstandings related to the OAuth term "resource owner" and the term "legal owner", this profile uses the term "user" instead.

**Proposed Change**  Can't suggest a change until I understand it

**Comment by msmock** [comment]
The intention of this statement is: It's a well known problem that OAuth uses the term "resource owner" for the user, who authorizes the application access to the data. The term "resource owner" suggests, that the user has the property rights on the data, can determine who has access to the data, etc. While this might be the case if you use Google and want to allow other applications to access your Google data, this is not true in general. The property rights on health data are assigned to the patients concerned (e.g, in the EU) or to the hospital the user is employed. To avoid this confusion, IUA uses the term "user" only.
