### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by gpavan19** [IHE/ITI.IUA#52]
**Section Number** *3.71.4.2.1    3.71.4.1.3     3.102.5 *

**Issue** *Some typos, in order with the section number write above:

3.71.4.2.1, in the sentence "  ... from an Authorization Client**. a** to obtain an access to…." 
3.71.4.1.3, in the sentence "The Authorization Server upon receiving a Get Token Request validates all request parameter.", miss “Access” in the sentence
3.102.5, comma typo In the second sentence, “At minimum ,the Authorization Server….” *

**Proposed Change** *correct the typo*

**Priority**: *Low*

**Comment by msmock** [comment]
fixed typos
