### ISSUE TITLE
IUA Public Comment - Felhofer

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#54]
I have put my public comment in a google spreadsheet

https://drive.google.com/file/d/13r7oyajsZulLr5CKUXLqZKvIB-t3uUZb/view?usp=sharing

Call me old-fashioned, but I think it will be difficult to random plow through these issues during public comment, rather than a spreadsheet/list that is sorted by section number.

I'm happy to create an issue for each row, if that's what the committee prefers.  Let me know.

**Comment by JohnMoehrke** [comment]
@lynnfel we have had trouble opening the spreadsheet, and would need write access to dispose of the issues.

**Comment by lynnfel** [comment]
Odd.  The permissions are "anyone with the link can edit".  The original comments in excel is attached.
[ITI_UUA_Comment_Form-felhofer.xlsx](https://github.com/IHE/ITI.IUA/files/5852307/ITI_UUA_Comment_Form-felhofer.xlsx)

**Comment by msmock** [comment]
Added comments on the google drive document. Opened issues for the TODO issues and added comments for the WONT-FIX and DONE issues.

**Comment by msmock** [comment]
[ITI_IUA_Comment_Form-felhofer-2021-01.xlsx](https://github.com/IHE/ITI.IUA/files/5872645/ITI_IUA_Comment_Form-felhofer-2021-01.xlsx)
