### ISSUE TITLE
alignment with SMART v2

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.IUA#57]
Here is the jira ticket with the high-level explanation of their changes in v2
https://jira.hl7.org/browse/FHIR-30578

**Comment by JohnMoehrke** [comment]
Here is their draft spec
http://build.fhir.org/ig/HL7/smart-app-launch/

**Comment by msmock** [comment]
I checked the new version and found no conflicts between SMART on FHIR and the current IUA version.

**Comment by msmock** [comment]
We reviewed the items in February 2021 and believe that SMART on FHIR and IUA can still work side by side.
