### ISSUE TITLE
markdown: URL with no hyperlink

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.IUA#59]
line 9 of Lynn's list: 

Sections 34.1.1.1 and 34.1.1.3

In markdown, is it possible to remove the 'auto-hyperlink' that appears for the canonical URI?  

Could we just make it courier new font with no hyperlink?

**Comment by msmock** [comment]
Gave a try to what is suggested by others. The only option that worked was to embed it in a code block, but that looks ugly, since it enforces a line break. Thus I left it like it is.

**Comment by JohnMoehrke** [comment]
@msmock did you try just single back quote? I see it as a recommendation

`http://foobar.com`

the others involved escaping a random character in the URL, or using span around some random characters in the URL. But these would seem to me to cause copy/paste errors. I am not sure, just guessing at that problem.
