### ISSUE TITLE
ITI 71 does not follow transaction template

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#6]
**Section Number**  Under Section 4, I expect to see a message type, followed by Trigger Events, Message Semantics, then Expected Actions (this one exists).   If there are portions of this transaction that are specific to one of the options in Vol 1, it should be contained in a subsection with the Option name (that can then be referenced from Vol 1.

Also, in Sec 3.71.4, the flow contains a combination of ITI-103, 71 and 72.  This cross-transaction interaction belongs in Vol 1 (ITI-71 should be standalone).

**Comment by msmock** [comment]
Should the figure in 3.71.4 look like the attached one? 

![get-auth-token](https://user-images.githubusercontent.com/536370/98645001-9976c700-2331-11eb-98b7-b9a724f8519a.png)

**Comment by msmock** [comment]
adapted to the profile template
