### ISSUE TITLE
optionality of grant types

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.IUA#61]
Line 11 of Lynn's list. 

Section 3.71.4.1.2.

This transaction supports two distinct grants for obtaining an access token: the Client Credential Grant type and the Authorization Code Grant Type.

Are the Auth Client and Auth Server actors required to support both grant types?  Just the Server (and the client can choose)?

**Comment by msmock** [comment]
I agree. 

To be discussed: 
Does everybody agree to make the two grant types mandatory for the Authorization Server and let the Authorization Client select one?

**Comment by slagesse-epic** [comment]
I don't think it is to hard to imagine an Authorization Server that only supports one grant type, for example, an authorization server that supports only backend applications might not want to support the Authorization Code Grant Type. 

So I think both types need to be optional for both client and server (where at least one must be supported).

**Comment by msmock** [comment]
While many options are handy in specifications and projects, they are cumbersome when it comes to testing at the connectathon or product evaluation in biddings. You not only need to know which profile the product implements but also must care of the various options. Therefore I try to keep the number of options low. 

The Client Credential and the Authorization Code grant types are the basic grant types which are defined in the core OAuth 2.1 specification. Thus, I expect vendors of IUA authorization server to implement both to be of general use.   

I vote for making both mandatory for the IUA authorization server.

**Comment by msmock** [comment]
The draft version already mandates both grant types for the authorization server in 34.1.1.2.

**Comment by msmock** [comment]
Fixed by adding the requirement to the Authorization Client to at least support on the two grant types profiled in IUA.
