### ISSUE TITLE
BPPC dependency in ITI-71

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#7]
**Section Number** 3.71.4.2.2.2
You say, "In an environment which uses the IHE BPPC profile for documenting the consent, the Authorization Server and Resource Server SHALL support the following extension parameter:...."

This is a "SHALL" statement associated with another profile.  That is allowed, but then you need add a requirement in Vol 1 Actor Groupings that the Auth Server and Resource Server shall be grouped with a BPPC Content Consumer

**Comment by msmock** [comment]
I copied this statement from the previous working version. I understand this as a conditional requirement: If you group with BPPC Content Consumer, the actors "SHALL support the following extension parameter", but I'm open to change the statement.

**Comment by msmock** [comment]
Don't know how to handle it. 

I compared that with XUA which has a similar requirement: 

_When the Authz-Consent Option is supported and a policy identifier needs to be sent, the X-Service User shall include the document unique ID of the Patient Privacy Policy Acknowledgement Document or include the Patient Privacy Policy Identifier for a policy that has been previously published encoded as SAML attributes._

but no requirement on grouping with the BPPC Content Consumer:
<img width="714" alt="Screen Shot 2020-11-11 at 07 07 19" src="https://user-images.githubusercontent.com/536370/98775157-d358d380-23ec-11eb-9427-af2993778a30.png">

**Comment by msmock** [comment]
Won't fix.
