### ISSUE TITLE
clarify location of client_id and client_secret in token request semantics of ITI-71

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#77]
This issue applies to IUA Rev 2.1 Trial Implementation, published March 19. 2021

CLIENT CREDENTIALS GRANT TYPE:
—> ITI-71 Message Semantics for Client Credentials Grant type token request (https://profiles.ihe.net/ITI/IUA/index.html#3714121-client-credential-grant-type) specifies that the client_id and client_secret goes in the HTTP header of the POST to request the token

—> And Figure 3.71.4.1.2.1-2 also indicates that client_id and client_secret go in the HTTP header.

CODE AUTHORIZATION GRANT TYPE:
—>ITI-71 Message Semantics for the Code Authorization Grant type request (https://profiles.ihe.net/ITI/IUA/index.html#3714122-authorization-code-grant-type)  indicates that the client_id goes in the HTTP request body of the HTTP POST to request the token.

—> the text prior to Figure 3.71.4.1.2.2-3 seems to be a copy/paste error from client_credentials above, indicating that both client_secret and client_id belong in the header… (client_secret is not specified for code authorization).   The example in the figure shows client_id in the header and not in the body.

QUESTION:  Is it intentional that client_id goes in the HTTP header for the client credentials grant type, but it goes in the body for the code authorization grant type?

**Comment by msmock** [comment]
It looks to me that the question compares two very different things: 

In the authorization code grant flow retrieving the token is a two step process. First the authorization request is performed to get the authorization code sending the client_id in the http header. In the second step the authorization code is used to retrieve the access token sending the client_id with the body of the POST request.  

The client credential flow only uses one step with one http transaction sending the client_id in the http header, just like the first step in the authorization code flow.

**Comment by lynnfel** [comment]
Yes, I understand that the client-credential flow is one step and the code-authorization is two step.

The screen shot below is ITI-71 text describing step 2 of the authorization code step.  I believe the text underlined in red contradicts what is marked in green.   Am I misunderstanding????
![1](https://user-images.githubusercontent.com/47753616/116419487-b8dfae80-a802-11eb-9279-7650d1147bf6.jpg)

**Comment by msmock** [comment]
Dear Lynn 

sorry I misunderstood the question. 

Yes you are right. In the second http call of the authorization code flow the client authentication via the client_id and client_secret is not required anymore in the latest version of the OAuth specification, Section 4.1. 

Now it reads: 
When making the request, the client authenticates with the authorization server if it can.
Thus client authentication using the client_id and client_secret in the http authorization header is optional. 

Formally the example is still correct for those using this way for client authorization but may be misleading. 

Kind regards
Martin

**Comment by lynnfel** [comment]
This change is tracked as CP-ITI-1256:  https://docs.google.com/spreadsheets/d/1gdr_Y8xZBvbb326J4z67cqprxOexFgtkPj_VlD3rB9E/edit#gid=0
