### ISSUE TITLE
Clarify that client_id is required, if known in the request to the token endpoint for Authorization Code grant type

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.IUA#78]
In 3.71.4.1.2.2 Authorization Code grant type, add "if known" to client_id (the text shows it's conditional).  This matches the optionality above in the HTTP GET request to the authorization endpoint.

...
The Authorization Client makes a HTTP POST request to the token endpoint with the following parameters in the HTTP request entity-body [OAuth 2.1, Section 4.1.3]:

    grant_type (required): The value shall be "authorization_code".

    code (required): The authorization code received from the Authorization Server in the authorization response.

    redirect_uri (required): The redirect URI of the Authorization Client callback. The value shall match the redirect URI the Authorization Client is registered at the Authorization Server and the value of the redirect_uri, if presented in the authorization request.

    client_id (required, **if known**): The client identifier the Authorization Client is registered with at the Authorization Server, if no other authentication scheme is used for client authentication.

**Comment by msmock** [comment]
According to the OAuth Core specification the client must identify using a client_id or other reliable authentication methods. This is mentioned in the introduction sections of IUA. 

It must be clear from reading IUA that the client_id may be dropped only if there are other reliable client authentication methods used. Thus I suggest not to add a **if known** but a **conditional** with a remark in the text below.

**Comment by msmock** [comment]
I checked what is written in the OAuth 2.1 specification: In Section "4.1.3. Access Token Request" the OAuth 2.1 core specification states: 

   "client_id":  REQUIRED, if the client is not authenticating with the authorization server as described in Section 3.2.1.

While section 3.2.1 and sections cited within mention other client authentication methods which uniquely identify the client. 

It should be discussed if we no longer want the client to identify with a client_id but enforce other client identification methods in IUA, if the vendors require this.

**Comment by lynnfel** [comment]
I agree with this recommendation.   It can be confirmed in a future discussion in ITI tech

**Comment by lynnfel** [comment]
This change is tracked as CP-ITI-1257:  https://docs.google.com/spreadsheets/d/1gdr_Y8xZBvbb326J4z67cqprxOexFgtkPj_VlD3rB9E/edit#gid=0

**Comment by msmock** [comment]
Solved with CP-ITI-1257
