### ISSUE TITLE
title above search bar says IHE HIE Whitepaper

### ISSUE THREAD

**Issue by MaryLJ** [IHE/ITI.IUA#87]
**Section Number** page header

**Issue** title above search bar says IHE HIE Whitepaper

**Proposed Change** Change to say IHE IUA Supplement

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by msmock** [comment]
<img width="1196" alt="Screenshot 2023-04-26 at 20 09 11" src="https://user-images.githubusercontent.com/536370/234665451-86e59c2e-843e-414a-9f04-b92dd0eb84a2.png">

**Comment by JohnMoehrke** [comment]
This is a problem caused during the publication. When we re-publish, we will not make the same mistake.
